data:
 build: jenkins-data
master:
 build: jenkins-master
 volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  - /usr/bin/docker:/usr/bin/docker
 volumes_from:
  - data
 ports:
  - "8088:8080"
  - "50000:50000"